--- #YAML:1.0
name: DateTime-Event-Lunar
version: 0.01
license: perl
distribution_type: module
requires:
  DateTime: 0
  DateTime::Set: 0
  DateTime::Util::Astro::Moon: 0
  DateTime::Util::Astro::Sun: 0
  DateTime::Util::Calc: 0
  Math::Round: 0
  Params::Validate: 0
recommends:
  Math::BigInt::GMP: 0
  Memoize: 0
  perl: 5.6.1
build_requires: {}
conflicts: {}
provides:
  DateTime::Event::Lunar:
    file: lib/DateTime/Event/Lunar.pm
    version: 0.01
generated_by: Module::Build version 0.21
