abstract: Compute Lunar Events
author: Copyright (c) 2004-2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: DateTime-Event-Lunar
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime: 0
  DateTime::Set: 0
  DateTime::Util::Astro: 0.09
  DateTime::Util::Calc: 0.13
  Math::Round: 0
version: 0.05
